name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ting-tong-pwa/
        server-dir: /public_html/autoinstalator/wordpresspluslscache1/wp-content/themes/tingtong/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
